# Generated by Django 5.0.3 on 2024-03-26 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Название изделия')),
                ('product_order_code', models.CharField(max_length=200, verbose_name='Артикул изделия')),
                ('product_price', models.FloatField(verbose_name='Цена изделия')),
                ('product_price_currency', models.CharField(max_length=3, verbose_name='Валюта цены')),
            ],
            options={
                'verbose_name': 'Комплектующее изделие',
                'verbose_name_plural': 'Комплектующее изделие',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(max_length=200, verbose_name='Шифр проекта')),
                ('project_description', models.CharField(max_length=400, verbose_name='Описание проекта')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=100, verbose_name='Название фирмы поставщика')),
                ('supplier_email', models.CharField(max_length=50, verbose_name='Почта поставщика')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='PositionalTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50, verbose_name='Позицоинное обозначение')),
                ('product', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.product')),
                ('project', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.project')),
            ],
            options={
                'verbose_name': 'Поз. обозначение',
                'verbose_name_plural': 'Поз. обозначения',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.supplier'),
        ),
    ]
