# Generated by Django 5.0.3 on 2024-03-26 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=100, verbose_name='Полное название раздела')),
                ('code_name', models.CharField(max_length=10, verbose_name='Кодовое обозначение раздела')),
            ],
            options={
                'verbose_name': 'Раздел документации',
                'verbose_name_plural': 'Разделы документации',
            },
        ),
        migrations.AddField(
            model_name='positionaltag',
            name='docsection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.docsection'),
        ),
    ]
