# Generated by Django 5.0.3 on 2024-04-01 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_positionaltag_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionaltag',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.product'),
        ),
    ]
