# Generated by Django 5.0.3 on 2024-04-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_positionaltag_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_manufacturer',
            field=models.CharField(max_length=50, null=True, verbose_name='Завод-изготовитель'),
        ),
    ]
