# Generated by Django 5.0.3 on 2024-04-09 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_product_manufacturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='Название свойства')),
            ],
            options={
                'verbose_name': 'Название свойства',
                'verbose_name_plural': 'Названия свойства',
            },
        ),
        migrations.CreateModel(
            name='Property_value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200, verbose_name='Значение свойства')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('property_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.property_name')),
            ],
            options={
                'verbose_name': 'Значение свойства',
                'verbose_name_plural': 'Значения свойств',
            },
        ),
    ]
